### ISSUE TITLE
Block Log Splitting

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#57] opened 2022-08-24 13:49 UTC
#### Opportunity: What are the needs of our target user groups?

Ability to serve requests for block logs not stored locally: users need a way to relay requests for block logs not stored locally to other nodes in order to have lighter weight nodes running at lower cost at scale while retaining the ability to fulfill older requests. A layered API approach is recommended as a starting point as work progresses on the additional scope of work.

Ability to chunk/split block logs: users need to be able to break up the block logs in order to manage older history on slower, less expensive storage.

Ability to reference and manage split block logs: users need to be able to access the chunked logs in order to fulfill older get block requests to host old P2P blocks.

Ability to share split block logs between nodeos instances: users need to be able to share the split block logs between nodeos instances in order to improve the speed and efficiency that a node can achieve an in-sync state. In order to achieve this, blocks.log splitting should be uniform.

Ability to configure between splitting solution and hole punching functionality introduced in 3.1: we will retain functionality for users so they can utilize the blocks.log management strategy that best suits their needs.

#### Target audience: Who is the target audience and why? 

- BPs
- API Providers
- dApp developers

#### Strategic alignment: How does this problem align with our core strategic pillars?

Blockchain made easy
- Less expensive infrastructure is easier
- Ability to share chunked block logs with other nodeos instances to swarm download is easier

### Context

In release v.2.1.0 block.log splitting was introduced, but not fully useable because you could only archive the blocks in a different directory than nodeos could reference. It is a requirement that the blocks.log can be chunked/split, but also that the split files remain easily reference-able for various history requests. There is strong support for a metadirectory feature that would allow block logs to be swept wherever desired. Only one directory should be required for an initial implementation of this functionality.

#### Competitors: Who are our top competitors (up to 5) and why? How do they solve this problem today?

Erigon allows finding of peers and backfilling state. Takes about 20 min to get up and running and backfills remainder over several days.

#### Solution name: How should we refer to this product opportunity?

Block Log Refactor

#### Purpose: Define the product’s purpose briefly

To support the ability to split a block log and manage the split files in a user-friendly way. To be able to share historical block log data that has been split and stored in lower cost solutions.

#### Additional tasks
- [ ]

**Comment by huangminghuang** [comment] 2022-11-08 19:08
I don't quite get why the  v.2.1.0 block.log splitting is not fully useable. It has two levels of log splitting, the `retained` level means the log is split yet _being able to_ referenced by nodeos and the `archive` level means the log is split and NOT being able to referenced by nodeos. You are allowed to set them to fulfill your need.  For example, if you set the log split stride to be 1000, and `max-retained-block-files` to 10 and , that means at any given time,  nodeos is able to reference the latest 10000 blocks. Any blocks beyond the latest 10000 block could possibly not be reference-able and will be in the archive dir. The user are safely to move or remove all the files in archive dir because they are no longer referenc-able.

**Comment by matthewdarwin** [comment] 2022-11-08 19:15
The problem is that the retained blocks cannot be put in a **separate** directory. Must always be in the "blocks" directory.
I used retained blocks config fine.

**Comment by huangminghuang** [comment] 2022-11-08 22:53
So the requirement is that retained blocks should be able to put in a separate directory?

**Comment by matthewdarwin** [comment] 2022-11-08 22:58
Yes.  I would want it to be on a different storage medium as the basic requirement.

Ideally it could be on network attached storage, where we can share blocks between different nodeos instances.  In that case nodeos should handle if the files appear/disappear.  (eg another nodeos might manage the files that this nodeos is looking at).

Separately there was a discussion if the block "stride" files should have standardized chunk sizes so they can be easily used for "bit torrent download" or whatever later feature where we can fast sync from another node.

**Comment by heifner** [comment] 2022-11-10 15:09
What standard stride size should be used?

**Comment by heifner** [comment] 2023-03-06 18:29
https://github.com/AntelopeIO/leap/pull/532

**Closed** 2023-06-02 00:28 UTC
Labels: initiative, SOW2, core, nodeos/cleos
